# Generated by Django 3.2.25 on 2024-03-30 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('taster_name', models.CharField(blank=True, max_length=254, null=True)),
                ('variety', models.CharField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(blank=True, max_length=254, null=True)),
                ('region', models.CharField(blank=True, max_length=254, null=True)),
                ('vintage', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('winery', models.CharField(blank=True, max_length=254, null=True)),
                ('ABV', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
